/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as PostsImport } from './routes/posts'
import { Route as Layout1Import } from './routes/_layout1'
import { Route as IndexImport } from './routes/index'
import { Route as UserUsernameImport } from './routes/user.$username'
import { Route as PostPostIdIndexImport } from './routes/post/$postId/index'
import { Route as Layout1UserIndexImport } from './routes/_layout1/user/index'
import { Route as Layout1PostIndexImport } from './routes/_layout1/post/index'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PostsRoute = PostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const Layout1Route = Layout1Import.update({
  id: '/_layout1',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUsernameRoute = UserUsernameImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRoute,
} as any)

const PostPostIdIndexRoute = PostPostIdIndexImport.update({
  id: '/post/$postId/',
  path: '/post/$postId/',
  getParentRoute: () => rootRoute,
} as any)

const Layout1UserIndexRoute = Layout1UserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => Layout1Route,
} as any)

const Layout1PostIndexRoute = Layout1PostIndexImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => Layout1Route,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout1': {
      id: '/_layout1'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Layout1Import
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameImport
      parentRoute: typeof rootRoute
    }
    '/_layout1/post/': {
      id: '/_layout1/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof Layout1PostIndexImport
      parentRoute: typeof Layout1Import
    }
    '/_layout1/user/': {
      id: '/_layout1/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof Layout1UserIndexImport
      parentRoute: typeof Layout1Import
    }
    '/post/$postId/': {
      id: '/post/$postId/'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface Layout1RouteChildren {
  Layout1PostIndexRoute: typeof Layout1PostIndexRoute
  Layout1UserIndexRoute: typeof Layout1UserIndexRoute
}

const Layout1RouteChildren: Layout1RouteChildren = {
  Layout1PostIndexRoute: Layout1PostIndexRoute,
  Layout1UserIndexRoute: Layout1UserIndexRoute,
}

const Layout1RouteWithChildren =
  Layout1Route._addFileChildren(Layout1RouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof Layout1RouteWithChildren
  '/posts': typeof PostsRoute
  '/search': typeof SearchRoute
  '/about': typeof AboutLazyRoute
  '/user/$username': typeof UserUsernameRoute
  '/post': typeof Layout1PostIndexRoute
  '/user': typeof Layout1UserIndexRoute
  '/post/$postId': typeof PostPostIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof Layout1RouteWithChildren
  '/posts': typeof PostsRoute
  '/search': typeof SearchRoute
  '/about': typeof AboutLazyRoute
  '/user/$username': typeof UserUsernameRoute
  '/post': typeof Layout1PostIndexRoute
  '/user': typeof Layout1UserIndexRoute
  '/post/$postId': typeof PostPostIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout1': typeof Layout1RouteWithChildren
  '/posts': typeof PostsRoute
  '/search': typeof SearchRoute
  '/about': typeof AboutLazyRoute
  '/user/$username': typeof UserUsernameRoute
  '/_layout1/post/': typeof Layout1PostIndexRoute
  '/_layout1/user/': typeof Layout1UserIndexRoute
  '/post/$postId/': typeof PostPostIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/posts'
    | '/search'
    | '/about'
    | '/user/$username'
    | '/post'
    | '/user'
    | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/posts'
    | '/search'
    | '/about'
    | '/user/$username'
    | '/post'
    | '/user'
    | '/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/_layout1'
    | '/posts'
    | '/search'
    | '/about'
    | '/user/$username'
    | '/_layout1/post/'
    | '/_layout1/user/'
    | '/post/$postId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Layout1Route: typeof Layout1RouteWithChildren
  PostsRoute: typeof PostsRoute
  SearchRoute: typeof SearchRoute
  AboutLazyRoute: typeof AboutLazyRoute
  UserUsernameRoute: typeof UserUsernameRoute
  PostPostIdIndexRoute: typeof PostPostIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Layout1Route: Layout1RouteWithChildren,
  PostsRoute: PostsRoute,
  SearchRoute: SearchRoute,
  AboutLazyRoute: AboutLazyRoute,
  UserUsernameRoute: UserUsernameRoute,
  PostPostIdIndexRoute: PostPostIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout1",
        "/posts",
        "/search",
        "/about",
        "/user/$username",
        "/post/$postId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout1": {
      "filePath": "_layout1.tsx",
      "children": [
        "/_layout1/post/",
        "/_layout1/user/"
      ]
    },
    "/posts": {
      "filePath": "posts.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/user/$username": {
      "filePath": "user.$username.tsx"
    },
    "/_layout1/post/": {
      "filePath": "_layout1/post/index.tsx",
      "parent": "/_layout1"
    },
    "/_layout1/user/": {
      "filePath": "_layout1/user/index.tsx",
      "parent": "/_layout1"
    },
    "/post/$postId/": {
      "filePath": "post/$postId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
